// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/proof/generate": {
            "post": {
                "description": "Submits a proof generation request to the background worker and returns a job ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proof"
                ],
                "summary": "Generate a ZK proof asynchronously",
                "parameters": [
                    {
                        "description": "Proof Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ProofRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.JobResponse"
                        }
                    }
                }
            }
        },
        "/proof/status/{id}": {
            "get": {
                "description": "returns the current status and result (if completed) of a proof generation job.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proof"
                ],
                "summary": "Get proof generation job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.JobStatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.JobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "status": {
                    "description": "\"pending\", \"processing\", \"completed\", \"failed\"",
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "main.JobStatusResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "issued_at": {
                    "type": "integer"
                },
                "job_id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/main.ProofResponse"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "main.ProofRequest": {
            "type": "object"
        },
        "main.ProofResponse": {
            "type": "object",
            "properties": {
                "commitment": {
                    "description": "Commitment hash",
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "proof": {
                    "description": "Serialized proof",
                    "type": "string"
                },
                "public_inputs": {
                    "description": "Public inputs as hex strings",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Noah Prover API",
	Description:      "Prover service for Noah ZK Identity system. Handles asynchronous ZK proof generation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
